linters:
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - errcheck
    - gocyclo
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - rowserrcheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "(G501|G401):"
    - linters:
        - maligned
      path: "^(conf/configuration|model/album|model/mediafile|server/subsonic/responses/responses)\\.go$"

